### ISSUE TITLE
[Feat] [TNGFUE] Improve TNGFUE execution flow and related tasks

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#614]
## Issue Description

Hello,

After executing the instructions from the [docs regarding TNGFUE deployment](https://free5gc.org/guide/TNGF/tngfue-installation/), I'd like to suggest some improvements.

### What's the version are you using

free5GC v3.4.3 + TNGFUE ([4ef9ccb](https://github.com/free5gc/tngfue/commit/4ef9ccb956cc32d94857295d711f0156e7a66acd)) on Ubuntu Server 20.04.6 LTS (more details on [this forum post](https://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571))

### Is your feature request related to a problem? Please describe.
[As reported on the forum](https://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571), I had some issues to setup the environment. However, this feature request is focused on improving the execution flow in general.

### Describe the solution you'd like
On one hand, the script run.sh was heavily based on N3IWUE's scripts to [run](https://github.com/free5gc/n3iwue/blob/main/run.sh) and [clean](https://github.com/free5gc/n3iwue/blob/main/clean.sh) the execution environment and on [free5GC itself](https://github.com/free5gc/free5gc/blob/main/run.sh). 

On the other hand, the prepare.sh was created to simplify the compilation steps written in the docs page while keeping the settings easy to adapt by changing the variables on the beginning of each file.

The main goal is to improve efficiency.

### Describe alternatives/workarounds you've considered
N/A

### Additional context
N/A

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [x] Yes, I have the time and I know how to start. (actually, it's already in a "work in progress" state. See linked PR)

### TODO

I'll leave the list below for future reference, so I can work on those steps if you give me permission to implement the suggested changes.

- [x] Implement a script to install prerequisites 
- [x] Implement a script to run TNGFUE
- [x] Test the new scripts successfully (currently, I'm facing the issues I reported [on the forum](https://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571)) (update: It was possible to test them, see [this message](https://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571/6?u=oliveiraleo))
- [ ] ~~Test the TNGFUE setup on a different subnet~~ (to be done later, see [this comment below](https://github.com/free5gc/free5gc/issues/614#issuecomment-2418122850))
- [x] Update README to reflect the new execution flow (will be added to the linked PR later) (done in https://github.com/free5gc/tngfue/pull/2#commits-pushed-ce19d2a)
- [x] Update the docs to streamline the configuration steps according to the new scripts (done in https://github.com/free5gc/free5gc.github.io/pull/164)

TIA,
Leo.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571/5

**Comment by oliveiraleo** [comment]
After some testing and discussion, I've decided to leave the TNGFUE test on another subnet for later, so we can speed up the process of closing the current issue. The full discussion regarding this topic is available [on the forum](https://forum.free5gc.org/t/running-tngfue-on-another-subnet/2571). If needed, I can open a separate issue later and link it here.
